### ISSUE TITLE
Add a panel to manage the local dictionary

### ISSUE THREAD

**Issue by rhadamanthe** [rhadamanthe/host-grabber-pp#19]
This panel should be able to:

* List hosts.
* Allow to edit them.
* Allow to create new ones.
* Allow to remove some of them.
* Visualize the XML output (e.g. for contributions or sharing).
* Import from XML.

**Comment by rhadamanthe** [comment]
Now considered as a duplicate of #35.

**Comment by strkven** [comment]
Hi,  
<host id="x">
  <domain>
  i.redd.it
  </domain>
  <path-pattern>
  <![CDATA[.+]]>
  </path-pattern>
  <search-pattern>
  <![CDATA[self]]>
  </search-pattern>
</host>
