### ISSUE TITLE
500px

### ISSUE THREAD

**Issue by TheSpawn74** [rhadamanthe/host-grabber-pp#66]
Hi!
Thank for your work!
Do you think it's possible to enable HG++ for working with 500px.com?
Thank you for your help!
Regards

**Comment by rhadamanthe** [comment]
Hello,

Sorry for the delay, I missed the notification. :x:  
I do not manage the catalog for everyone as I have a complicated schedule. However, I can review and integrate contributions. If you want to submit an entry for 500px.com, you are welcome.

[The documentation](https://rhadamanthe.github.io/host-grabber-pp/en/hosts-definition.html) explains what to add to [the catalog](https://github.com/rhadamanthe/host-grabber-pp-host.xml) to test it. There are also [debugging tools](https://rhadamanthe.github.io/host-grabber-pp/en/index.html#debugging) that really simplify the work. I can also help you if you encounter problems or if things need to be explained.
