### ISSUE TITLE
new link extraction strategy: cssquery

### ISSUE THREAD

**Issue by tzr7** [rhadamanthe/host-grabber-pp#71]
For some hosts the easiest way to extract the image link is by a css query.

The cssquery strategy could be configured with a css query string. The css query would return the img element. Then the src attribute can be used as download link.

css queries are very versatile.

For example this code snippet used in Image Host Grabber Classic extracts the image from the new imagevenue page format:
```
img = doc.querySelector("div.col-md-12 img");
if (img) {
    return {url: img.src, filename: img.alt, status: "OK"};
}
```
Example (family safe and creative commons license):
http://imagevenue.com/MENWU00

**Comment by rhadamanthe** [comment]
The next version will be released soon, with some bug fixes.  
I could add this strategy before the release. :)

**Comment by tzr7** [comment]
> The next version will be released soon, with some bug fixes.
> I could add this strategy before the release. :)

very cool indeed! But if it delays the next release, put it the following one.

Thank you very much for your excellent work!

**Comment by rhadamanthe** [comment]
Done. I still have to confirm it works with Imagevenue.

**Comment by tzr7** [comment]
I just did a quick test on a forum page with two imagevenue images.
This works:
<host id="x">
  <domain>
  imagevenue.com
  </domain>
  <path-pattern>
  <![CDATA[[A-Z]+]]>
  </path-pattern>
  <search-pattern>
  <![CDATA[CSS query: div.col-md-12 img]]>
  </search-pattern>
</host>

I am not sure, how stable the css query will work. 

Thank you very much!

**Comment by rhadamanthe** [comment]
I have added an entry for imagevenue in [my dictionary](https://github.com/rhadamanthe/host-grabber-pp-host.xml/blob/master/hosts.xml#L192).
I also confirmed that the old one was still working. So, HG++ will support both strategies, the filter being the path pattern.
