### ISSUE TITLE
download list does not open when multiple Browser Windows are open

### ISSUE THREAD

**Issue by tzr7** [rhadamanthe/host-grabber-pp#74]
- I have two Browser windows open, left and right. I do not remember the order I opened them.
- In the right window I selected "Extract and Download" from the context menu. 
- The download list tab did not open
- An error was shown in the browser console: 
  _Error: Opener tab must be in the same window as the tab being created_
- The one image on the page was downloaded
- I moved the tab with the image to the left window 
- Extract and Download again
- the download list tab now opened and it contained the element from the download before.

**Comment by rhadamanthe** [comment]
It looks like a real bug.
