### ISSUE TITLE
Host File question.

### ISSUE THREAD

**Issue by junomarian** [rhadamanthe/host-grabber-pp#77]
Does it support host file from IGH the old 
famous extension? I am using IGH 
on Palemoon its host file was updated in Jan 2020. But IGH have problems, closes itself in middle of downloads. 

It would be great if all hosts are added from igh to this igh++

**Comment by rhadamanthe** [comment]
Hi,

No, the extension does not support IHG's catalog.  
IHG supports several strategies to download images. Some of them are compliant with the ones in this extensions (by ID and by class names, as an example). There are almost no changes to do. Some others are incompatible.

There have been major changes in Firefox when they switched to web extensions.
This is also why the developement team of IHG did not upgrade it. It was too much work: it was about starting from zero again. HG++ does not work the same way at all than IHG and they way host files are defined reflects it. I kept the good ideas of IHG when I shaped the host file. But we cannot realy on IHG's host file.
