### ISSUE TITLE
Allow to stop the downloading process

### ISSUE THREAD

**Issue by Lumox100** [rhadamanthe/host-grabber-pp#78]
Allow downloading of only the selected images and have a button to be able to stop the downloading process.

In content script, check for selection of content with

isContentSelected: function() {
	  return !document.getSelection().isCollapsed;
	}

**Comment by rhadamanthe** [comment]
Hi,

There is a new feature in thext version, about [downloading only the selection](https://github.com/rhadamanthe/host-grabber-pp/issues/10). But why would it be related to stopping the download?

The selection is done in the web page and doing a right click.  
You seem to suggest another approach by checking / unchecking the found images in the download tab. Am I right?

**Comment by Lumox100** [comment]
Hi

Sorry for the confusion. The 2 functions I requested are unrelated.

1 - Be able to download only the selected images. Only the selected images in the web page would be listed on your "Download List" page.

2 - Once the downloading has begun, be able to stop the downloading of any remaining images in the list that have not already been downloaded or are currently downloading. This would be a button on your "Download List" page.

Thanks for the reply.

**Comment by rhadamanthe** [comment]
Given that downloading the selection is already implemented, I will consider this ticket as a demand for a stop button.

**Comment by rhadamanthe** [comment]
I will release the next version in few hours.
You will be able to test the download of a selection. The stop/resume actions have been added.
