### ISSUE TITLE
Can you, please, add imgspice.com host?

### ISSUE THREAD

**Issue by heltua** [rhadamanthe/host-grabber-pp#80]
Can you, please, add imgspice.com host? I found the rule [https://imagehostgrabber.com/hostf.html](here), but couldn't find the way to make it work in your addon. Thank you!

**Comment by rhadamanthe** [comment]
Hi,

I will take a look, no guarantee of result.

**Comment by heltua** [comment]
> 
> 
> Hi,
> 
> I will take a look, no guarantee of result.

Cool! I hope you'll figure it out!

**Comment by heltua** [comment]
BTW, imgspice works nicely with ImageHost Grabber. Tried it with legacy FF - the rule works!

**Comment by rhadamanthe** [comment]
Done.  
The file name is not pretty at the moment. Using the **alt** attribute will be possible as soon as #75 is implemented. I have recently resumed work on this other ticket.

**Comment by rhadamanthe** [comment]
The next catalog version will rely on the **alt** attribute to find the file name.
