### ISSUE TITLE
Reload dictionary flashes green even if the file doesn't exist

### ISSUE THREAD

**Issue by aalhazred1650** [rhadamanthe/host-grabber-pp#81]
I made a new pattern in the debug window, and I wanted to try it out. I downloaded the dictionary from github, and added my new XML to it. Then I added a file:/// URL for the dictionary URL and pressed Reload Dictionary. The box flashed green, so I assumed it worked. If I open the debug window again, my new entry is not in the dropdown list.

Turns out, if I put a non-existent file in the URL box, it *still* flashes green!

How can I use a local dictionary file?

(Firefox 80.0.1, HG++ 0.11, on Windows 10)

**Comment by rhadamanthe** [comment]
Hi,

You cannot use a local dictionary.
Please, see [this comment](https://github.com/rhadamanthe/host-grabber-pp/issues/21#issuecomment-573629087) for an explanation. The available options for the moment are listed in the same thread, right above.

**Comment by aalhazred1650** [comment]
OK, I can understand the security issue. I'll try with a local webserver instead.

What are the green flashes for then? This part of the user interface is not very clear... (e.g. what does Save Dictionary URL do?)

**Comment by rhadamanthe** [comment]
It means the URL is valid and that it was saved.
I could add a verification to prevent `file` schemes to be used. The background will thus be red.

**Comment by rhadamanthe** [comment]
Done. It will now flash it red if the dictionary URL starts with `file:/`.
I also fixed a bug when restauring the default URL.
