### ISSUE TITLE
Grabber does not grab

### ISSUE THREAD

**Issue by igorvolnyi** [rhadamanthe/host-grabber-pp#89]
Image hosts where HG++ fails:
imagetwist.com
imgbox.com
imagebam.com

**Comment by rhadamanthe** [comment]
Hi!

Which version of the extension are you using?
Do you use the official dictionary or an old fork?

**Comment by igorvolnyi** [comment]
Last official version. 0.12 at the moment. Installed from official FF addons site.

**Comment by rhadamanthe** [comment]
And the catalog in the preferences?
Is it [the official one](https://raw.githubusercontent.com/rhadamanthe/host-grabber-pp-host.xml/master/hosts.xml)?

**Comment by igorvolnyi** [comment]
Dammit! At some moment I changed it to a local copy. My bad.
