### ISSUE TITLE
More than one image link in one line are not recognized (imgspice)

### ISSUE THREAD

**Issue by sc242** [rhadamanthe/host-grabber-pp#90]
If there is more than one link in a line (means no line breaks in the HTML code), only the first image link will be recognized and downloaded.
At least I noticed the problem with imgspice.

`<a href="https://imgspice.com/nrlos66odr7d/img__002.jpg.html" target="_blank" class="link link--external" rel="noopener"><img src="https://img24.imgspice.com/i/07041/nrlos66odr7d_t.jpg" data-url="https://img24.imgspice.com/i/07041/nrlos66odr7d_t.jpg" class="bbImage " style="" alt="" title="" /></a> <a href="https://imgspice.com/qr4bn1sfp1r6/img__003.jpg.html" target="_blank" class="link link--external" rel="noopener"><img src="https://img24.imgspice.com/i/07041/qr4bn1sfp1r6_t.jpg" data-url="https://img24.imgspice.com/i/07041/qr4bn1sfp1r6_t.jpg" class="bbImage " style="" alt="" title="" /></a> <a href="https://imgspice.com/flri7gygudf8/img__004.jpg.html" target="_blank" class="link link--external" rel="noopener"><img src="https://img24.imgspice.com/i/07041/flri7gygudf8_t.jpg" data-url="https://img24.imgspice.com/i/07041/flri7gygudf8_t.jpg" class="bbImage " style="" alt="" title="" /></a>`

**Comment by rhadamanthe** [comment]
Hi!

I will have a look at this.

**Comment by rhadamanthe** [comment]
You were right.
It is fixed in the last version of the catalog. Thanks for reporting it. :+1:
