### ISSUE TITLE
Can't download from imagetwist.com

### ISSUE THREAD

**Issue by igorvolnyi** [rhadamanthe/host-grabber-pp#91]
Example:
[http://www.planetsuzy.org/showpost.php?p=11474030&postcount=9](http://www.planetsuzy.org/showpost.php?p=11474030&postcount=9)

**Comment by igorvolnyi** [comment]
This one worked Ok
[http://www.planetsuzy.org/showpost.php?p=22010793&postcount=58](http://www.planetsuzy.org/showpost.php?p=22010793&postcount=58)

**Comment by rhadamanthe** [comment]
Hi!

This is weird, it works fine for me with the first page you mentioned.
Maybe Image Twist was having some maintenance on servers the day you tried it?

Can you confirm it works now?

**Comment by igorvolnyi** [comment]
It does work now. But at the time of the report it in some cases did and in some cases didn't.
