### ISSUE TITLE
IHG++ forgets custom pattern for the directory name when quitting FF

### ISSUE THREAD

**Issue by igorvolnyi** [rhadamanthe/host-grabber-pp#95]
My custom pattern for the directory name is "%title%/%year%-%month%-%day%_%hour%.%minute%/". If I save it in options and continue using IHG++, the directory structure is hierarchical. But if I quit FF and launch it again, IHG++ "forgets" the custom pattern and the Downloads directory becomes just a plain pile of images.

**Comment by rhadamanthe** [comment]
Hello,

I will investigate it.

**Comment by rhadamanthe** [comment]
Hello.
I finally fixed it. I am exploring a new feature and then, I will deliver a new release. Thank you for your patience.

**Comment by igorvolnyi** [comment]
Almost two years... Where is the release?
